spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - SaveSession
      routes:
        - id: book-service
          uri: http://127.0.0.1:8040
          predicates:
            - Path=/books-ws/**
          filters:
            - name: TokenRelay
            - RemoveRequestHeader=Cookie
  redis:
    connect-timeout: 30s
    host: localhost
    port: 6379
    timeout: 500ms
  session:
    store-type: redis
    timeout: 10m

  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8888/auth/realms/master/protocol/openid-connect/token
            authorization-uri: http://localhost:8888/auth/realms/master/protocol/openid-connect/auth
            userinfo-uri: http://localhost:8888/auth/realms/master/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          keycloak:
            provider: keycloak
            client-id: oauth2-login
            client-secret: 118cb43e-ae71-44f3-9484-3b61d1c8c4f7
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"

server.port: 8088

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE
management:
  endpoints:
    web:
      exposure:
        include: "*"
